def generate_summary(spectrum):
    print("\n============================================")
    print("                  ASTROSPEC REPORT")
    print("\n============================================")
    print("\nTarget:")
    print(spectrum.object_name)
    print("\nObservation:")
    print("Date:", spectrum.metadata.get("Date", "Not available"))
    print("Exposure:", spectrum.metadata.get("Exposure Time", "Not available"), "s")
    print("Instrument:", spectrum.metadata.get("Instrument", "Not available"))
    print("\nData:")
    print("Type:", spectrum.metadata.get("Type", "Unknown"))
    print("Data Points:", len(spectrum.flux))
    print("\nWavelength Calibration:")
    print("Starting Wavelength:", spectrum.fits_info["CRVAL1"], "Å")
    print("Dispersion:", spectrum.fits_info["CDELT1"],"Å/pixel")
    print("\nFlux Units:")
    print(spectrum.fits_info["BUNIT"])
    print("\n============================================")